result_4 = {'4001': 'a person holding a pair of scissors', '85': 'a man is standing next to a car', '4133': 'a person holding a cell phone in a room', '2593': 'a person holding a cell phone in a hand', '2637': 'a man sitting on the back of a car', '5629': 'a woman is sitting on a car with a surfboard', '3473': 'a person holding a computer mouse in a hand', '2725': 'a person holding a piece of broccoli on a table', '5585': 'a person holding a clock on top of a table', '4089': 'a man and a woman riding on a car with a horse', '5717': 'a person is holding a book on the bed', '4705': 'a black car is sitting on top of a skateboard', '2945': 'a person holding a pair of scissors', '3077': 'a man riding a bike on the side of a car', '2505': 'a man sitting on the back of a car', '4368': 'a woman is standing next to a train', '965': 'a man sitting on a car with a surfboard'}

result_5 = {'143': 'a black and white photo of a frisbee in the field', '2903': 'a man is standing in front of a mirror', '1303': 'a person holding a pair of scissors', '2083': 'a black and white photo of a traffic light', '2323': 'a man wearing a suit and tie standing in a room', '2763': 'a book is sitting on top of a fence', '2263': 'a man is standing on top of a plane', '3183': 'a man is holding a surfboard in the street'}

result_6 = {'2615': 'a dog is standing in the grass in a field', '2675': 'a bus is parked on the side of a street', '4955': 'a group of people riding motorcycles in a field', '4899': 'a man is standing on a train in the woods', '5675': 'a truck is driving down a road with a road', '5615': 'a person is walking down a street with an umbrella', '5075': 'a man is standing in the street with a truck', '4595': 'a man is walking down a road with a bus', '5555': 'a person is standing on a street holding an umbrella', '6815': 'a man is standing in the grass with a stop sign', '2075': 'a truck is parked on the side of a road', '4239': 'a person is walking down a street with an umbrella', '6177': 'a man is standing next to a bike with a dog', '8675': 'a person is standing in the grass with an umbrella', '5198': 'a man is sitting on top of a skateboard', '1955': 'a boat is sitting on top of a beach', '1564': 'a car is sitting on the side of a stop sign', '1535': 'a person is standing on the side of a car with a suitcase', '2015': 'a person is standing in the snow with a frisbee', '4895': 'a man is riding on top of a motorcycle', '6113': 'a group of people standing next to a truck'}

result_13 = {'732': 'a person holding a cat with a table', '820': 'a woman is holding a dog with a frisbee', '996': 'a man sitting on a couch in a living room', '1348': 'a dog is laying on top of a bed', '908': 'a black and white dog laying on a bed', '3394': 'a black and white photo of a person holding a skateboard', '3372': 'a black and white toothbrush is sitting on top of a bathroom'}

result_16 = {'5347': 'a woman standing in a kitchen preparing food', '1693': 'a woman sitting on a table with a bowl of fruit', '8943': 'a woman is standing in a kitchen with a cake', '4825': 'a pan of food on top of a stove', '7203': 'a sandwich on a plate of food on a table', '1287': 'a person is holding a knife on a cutting board', '6681': 'a sandwich on a plate of food on a table', '2507': 'a woman is standing next to a bowl of food', '6449': 'a person cutting a piece of carrots on a cutting board', '6855': 'a sandwich on a plate of food on a table', '8537': 'a woman is sitting at a table with a cake', '5695': 'a sandwich on a plate of food on a table', '7783': 'a person holding a piece of cake on a plate with a table', '5521': 'a sandwich on a plate of food on a table', '881': 'a person is standing in a field with a blue', '939': 'a woman standing in a kitchen with a table', '6217': 'a woman is sitting at a table with a plate of food', '1055': 'a person is sitting on a table with a cutting board', '1577': 'a woman is sitting at a table eating a piece of cake', '3286': 'a woman is standing next to a bowl of food'}

result_17 = {'4219': 'a woman standing in a kitchen with a table', '4991': 'a woman standing in a kitchen with a table', '5119': 'a woman standing in a kitchen with a sink', '4909': 'a woman is standing in a kitchen with a banana', '5335': 'a woman standing in a kitchen with a refrigerator', '1953': 'a woman standing in a kitchen preparing food', '4975': 'a plate of food on a table', '3932': 'a woman is standing in a kitchen with a sink', '3539': 'a woman sitting in a kitchen with a sink', '5028': 'a woman sitting at a table eating a sandwich', '4003': 'a person holding a pan of food on a table', '1699': 'a person holding a plate of food on a table', '849': 'a person is holding a white with a toothbrush', '4255': 'a person holding a plate of food on a table', '223': 'a sandwich on a plate with a table'}

result_26 = {'1856': 'a group of people standing next to a cell phone', '1781': 'a red train is sitting in a street with a table', '2316': 'a group of people standing next to a cell phone', '316': 'a sign on the side of a wall', '2156': 'a man holding a cell phone in a hand', '1276': 'a group of people standing next to a red and white cake', '296': 'a street sign on the side of a building'}

result_31 = {'2962': 'a man is standing in front of a frisbee', '2610': 'a man is standing next to a street sign', '1522': 'a black and white photo of a bird in the street', '4286': 'a street sign on the side of a fence', '626': 'a black cat is sitting on top of a toilet', '437': 'a man is standing in front of a bed with a table', '2546': 'a man and a woman holding a cell phone', '3346': 'a group of people walking down a street with umbrellas', '562': 'a black and white photo of a person holding a cell phone', '1042': 'a little girl is holding a cat', '3508': 'a man wearing a shirt and a tie', '3890': 'a black and white photo of a woman in a store', '3602': 'a group of people walking down a street with luggage', '1586': 'a woman is sitting on a toilet with a teddy bear', '3314': 'a man wearing a hat and a tie'}

result_41 = {'4697': 'a bird is flying over a field of grass', '5202': 'a man riding a dirt bike on a road', '4636': 'a group of people riding horses on a field', '2647': 'a man is holding a frisbee in the beach', '5186': 'a man riding a dirt bike on a field', '2501': 'a man riding a dirt bike on a road', '5036': 'a man is standing next to a dirt road', '1788': 'a young boy riding a motorcycle on a street', '4939': 'a man riding a motorcycle on a dirt road', '4586': 'a man is standing next to a horse in a field', '4786': 'a man flying through the air on a snowboard', '1744': 'a man riding a bike on a field', '4686': 'a man is flying a kite in the sky', '2486': 'a man riding a motorcycle on the side of a road', '4799': 'a man is walking on a beach with a mountain', '5039': 'a man is riding a horse on the beach', '4736': 'a man riding a horse in the air', '4886': 'a man riding a motorcycle on a road', '1708': 'a man riding a bike on the water', '4540': 'a herd of stuffed teddy bears in a tree', '4401': 'a man is standing next to a giraffe', '4486': 'a group of people flying a kite in a field', '5102': 'a man riding a motorcycle on the beach', '2436': 'a man is standing on top of a field', '5086': 'a cow standing in the grass in a field', '1686': 'a statue of a horse standing on the side of a beach'}

result_49 = {'429': 'a dog laying on top of a table', '1977': 'a man is standing next to a dog', '501': 'a dog laying on top of a table', '1257': 'a dog is sitting in front of a table', '5613': 'a woman is standing next to a dog', '717': 'a dog is sitting in front of a table', '2460': 'a man is standing next to a dog', '5037': 'a man is standing next to a dog', '4605': 'a man is standing next to a dog', '2877': 'a dog is sitting in the water', '3021': 'a man is standing next to a cow', '2841': 'a dog laying on top of a toilet'}
